name: neptune-example
on: [push]
jobs:
  set-up-neptune:
    runs-on: ubuntu-latest
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install neptune
      - name: Run your Python script
        run: python ../neptune.py
